### PR TITLE
fix for the newbucks hack

### PR DESCRIPTION
**Pull request by kernelxdev**
Before it had million of decimal numbers it wasn't readable + it didn't even work this should fix it.

Btw was with pinktarr/madminecraftr while coding :3

### CODE REVIEW

**Comment by MadMincraftr** [comment]
Technically I did help but also i didn't. I was just staring at your screen share thinking "hmmm this doesn't look right" but didn't care enough to say much. This is kinda my fault tbh

**Comment by kernelxdev** [comment]
Also you might want to change the maxvalue a little cuz its hard to setup less than like a trillion or add a inputfield where u can input how much newbucks you want to have

**Comment by ThatFinnDev** [comment]
I did it the way it's now for a reason. Because of the pow and all of that, the slider is no longer propertional. If it was (like in your pr), you only need to move the slider a teeny tiny bit to get millions of newbucks. You can't only give you e.g 5322 newbucks, if it's proportional. It basically either 0 or between 1000000 and 99999999 newbucks (I don't know how many digits, but it's a lot).

Also, if you want to give yourself a specific amount and not just a lot, you can use the `newbucks` command for this specific purpose.

P.S: If you create a pr, please apply the changes to the experimental branch for easier merging.

**Comment by kernelxdev** [comment]
ok

**Pull request closed without merging**
